version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    tty: true
    networks:
      - mynetwork
    
networks:
  mynetwork:
    name: mynetwork
    external: false



